image: atlassian/default-image:3

pipelines:
  branches:
    main:
      - step:
          name: Build and push 
          deployment: Production
          script:
            - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
            - IMAGE_NAME="iamrony777/gitpod-images"
            - docker build . --file Dockerfile --tag "$IMAGE_NAME:python"
            - docker push --all-tags "$IMAGE_NAME"
            - docker logout
          caches:
            - docker
          services:
            - docker
